service: FoodForThought

provider:
  name: aws
  runtime: nodejs12.x
  profile: default
  timeout: 30

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource: "*"

  s3:
    foodForThought2:
      name: foodforthought2
      versioningConfiguration:
        Status: Enabled

functions:
  foodForThoughts3Trigger:
    handler: handler.s3Trigger
    events:
      - s3:
          bucket: foodforthought2
          event: s3:ObjectCreated:*
          rules:
            - prefix: generic-food
            - suffix: .csv
    destinations:
      onSuccess: arn:aws:sns:us-east-1:453098623877:food-for-thought


resources:
  - ${file(resources/dynamo-table.yml)}
